name: Unit Tests Remote Target
on: [push, pull_request]
jobs:
    UnitTests:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run remote tests on the target platform
        run: platformio remote test -e esp32